org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.debug=false

minecraft_version=1.21.1
minecraft_version_range=[1.21,1.22)
neo_version=21.1.172
neo_version_range=[21.1,)
loader_version_range=[4,)

parchment_mappings_version=2024.11.17
parchment_minecraft_version=1.21.1

mod_id=ankinbt
mod_name=AnkiNBT
mod_license=MIT
mod_version=2.0.0
mod_group=com.ankinbt
mod_authors=AnkiNBT Team
mod_description=A modern client-side NBT editor with sleek translucent UI for Minecraft modpacks.
